services:
  - type: web
    name: orders-resolution-backend
    runtime: node
    region: oregon
    plan: free
    branch: main
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: LOG_LEVEL
        value: info
      - key: CORS_ORIGINS
        value: "*"
