/**
 * Constants for order and payment rules.
 */
export const ORDER_CONSTANTS = {
  MIN_LINE_ITEMS: 1,
  MAX_LINE_ITEMS: 50,
  MIN_QUANTITY: 1,
  MAX_QUANTITY: 10_000,
  MIN_UNIT_PRICE_CENTS: 1,
  MAX_UNIT_PRICE_CENTS: 100_000_000,
  MIN_PAYMENT_CENTS: 1,
  MAX_PAYMENTS: 200,
  MAX_CUSTOMER_LENGTH: 200,
  MAX_DESCRIPTION_LENGTH: 500,
  MAX_NOTE_LENGTH: 500,
  MIN_PAGE_SIZE: 1,
  DEFAULT_PAGE_SIZE: 20,
  MAX_PAGE_SIZE: 100,
  IDEMPOTENCY_KEY_MAX_LENGTH: 64,
} as const;
